### ISSUE TITLE
Publish on Packagist.org

### ISSUE THREAD

**Issue by IonBazan** [answear/poczta-polska-bundle#3]
The package is not published on packagist.org which makes it impossible to install it using `composer require answear/poczta-polska-bundle`:
```
[InvalidArgumentException]                                                                                                                                                                                
  Could not find a matching version of package answear/poczta-polska-bundle. Check the package spelling, your version constraint and that the package is available in a stability which matches your minim  
  um-stability (stable).   
```

**Comment by malarzm** [comment]
Indeed we forgot about it :sweat_smile: It's added now (https://packagist.org/packages/answear/poczta-polska-bundle), we'll tag 1.0.0 later today

**Comment by malarzm** [comment]
@IonBazan 1.0.0 is tagged now, should be available on packagist shortly :)
